### ISSUE TITLE
Publish latest version to CRAN

### ISSUE THREAD

**Issue by armintoepfer** [taiyun/corrplot#106]
I'd appreciate if you could upload the latest version to CRAN.

Thank you!
Armin

**Comment by vsimko** [comment]
I could do that, but @taiyun needs to confirm it, see:
https://cran.r-project.org/web/packages/policies.html

> If for some reason the submission has to be made by someone else (for example, a co-author) this needs to be explained, and the designated maintainer will need to confirm the submission.

**Comment by vsimko** [comment]
I can fix both problems listed here:
https://win-builder.r-project.org/incoming_pretest/171015_173415_corrplot_084/00check.log

**Comment by taiyun** [comment]
Just submitted again.
