### ISSUE TITLE
Return plot instead of matrix

### ISSUE THREAD

**Issue by DominiqueMakowski** [taiyun/corrplot#108]
For my current project, I would need to store the plot in an object (named `p` for example) and actually plot it later on in the script (using for example `plot(p)`). 

However, this is not possible currently as corrplot() automatically plots the figure (and cannot be delayed) and returns a correlation matrix instead of the plotted figure.

Is there a way to modify that behaviour?

Thanks

**Comment by vsimko** [comment]
Hi, what about simple closure like the following example:
```r
M <- cor(mtcars)

reuseMe <- function() {
  corrplot(M, method = "square")
}

reuseMe()
...
reuseMe()

**Comment by DominiqueMakowski** [comment]
It's a good idea, unfortunately, it doesn't work in my specific case, which I'll explain a bit more.

I'd like to create a function A, within which I create the corrplot, and then store it in a list returned by the function A.

Then, I'd like to actually display the corplot bycalling the plot object from the list.

Here's what I tried:
```r
A <- function(){
text <- "whatever else"

plot <- function() {
    p <- corrplot::corrplot.mixed(r, lower="ellipse", upper="number", order = "hclust", p.mat = p, sig.level = 0.05, insig="n", tl.pos="lt")
    return(p())
  }
return(list(text=text, plot=plot))
}
```

I'd like then to be able to do this to display the plot:
```r
output <- A()
output$plot  # And, by calling this object, display the plot
```

However, this returns the function code 😞 

```
function() {
    p <- corrplot::corrplot.mixed(r, lower="ellipse", upper="number", order = "hclust", p.mat = p, sig.level = 0.05, insig="n", tl.pos="lt")
    return(p())
  }
<environment: 0x000000001b0505f0>
```
Do you have any advices?
Thanks for your help!

**Comment by vsimko** [comment]
no problem, functional programming is our friend:
```r
library(corrplot)

# this function generates a list which contains a closure stored inside the "plot" element
prepareMyList <- function(r, p, text) {
  plot <- function() {
    # Note: variables "r" and "p" are bound from within the closure
    corrplot.mixed(r, lower = "ellipse", upper = "number",
                   order = "hclust", p.mat = p, sig.level = 0.05,
                   insig = "n", tl.pos = "lt")
  }
  list(text = text, plot = plot, p = p) # this is returned
}

A <- prepareMyList(cor(mtcars), .01, "whatever text")
```

```r
> print(A$text) # this shows the text value copied from the "text" parameter
[1] "whatever text"
```
```r
> print(A$p) # this shows the variable "p" bound by the closure
[1] 0.01
```
```r
A$plot() # this plots the plot bound by the closure
```
![image](https://user-images.githubusercontent.com/7080773/31189332-339d8fd4-a938-11e7-9a92-dd264db4912e.png)

**Comment by DominiqueMakowski** [comment]
Your help was more than useful. Closing this 😉
