### ISSUE TITLE
Add an example plot to your readme

### ISSUE THREAD

**Issue by Dasonk** [taiyun/corrplot#11]
For a package that creates a visual it makes a lot of sense to have at least an example of those visuals on the frontpage of your repo.  If you add something to your readme that could help get people excited about your package.

**Comment by jyfeather** [comment]
I agree. Although you put a link of demo there, visual examples still entertain people in the README. Maybe I could help add a few examples to README.

**Comment by taiyun** [comment]
Good idea. Many thanks @jyfeather

**Comment by jyfeather** [comment]
No Problem. You package is great.

*- Yan Jin*

**Comment by jyfeather** [comment]
Could you take a look at my modification of README file? @taiyun I hope it looks nice. Already submitted a pull request. Thank you.
![image](https://cloud.githubusercontent.com/assets/2344998/7328946/8295c784-ea8e-11e4-8da4-be4be3d6c54a.png)
