### ISSUE TITLE
license + code of conduct

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#112]
I would like to know your opinion on including the code of conduct into the project as suggested by github (Insights -> Community).

The following version seems reasonable to me:
https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

**Comment by vsimko** [comment]
Also, which license should we pick (DESCRIPTION contains just "GPL" in the license field)
- GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
or
- GNU GENERAL PUBLIC LICENSE Version 2, June 1991
or something else ?

**Comment by taiyun** [comment]
MIT ?

**Comment by vsimko** [comment]
I'm OK with the MIT license. The question is how to do it properly.
Some time ago, there was a discussion about relicensing within the package `digest`, although the question was GPL2->GPL3.

Here is the related issue:
https://github.com/eddelbuettel/digest/issues/36

If we convert to MIT, we need to write in `DESCRIPTION` the field `License: MIT + LICENSE` and then, we need to create a `LICENSE` file which contains just the following two lines (CRAN only accepts these two line templates, not the whole license text):
```
YEAR: 2009-2017
COPYRIGHT HOLDER: ... probably all contributors here ...
```

**Comment by taiyun** [comment]
There are much more lines in [ggplot2's license](https://cran.r-project.org/web/packages/ggplot2/LICENSE`)

**Comment by vsimko** [comment]
ok, it seems like license-specific stuff.
However, for the MIT license the CRAN reviewers definitely want exactly those two lines.
see https://cran.r-project.org/web/licenses/MIT
