### ISSUE TITLE
too many blank spaces at the top, bottom and left

### ISSUE THREAD

**Issue by jinzhen-lin** [taiyun/corrplot#115]
I recently updated to v0.84 from cran. And I find the version cause too many blank space at the top, bottom and left of the plot, especially when the number of variables is small.

For example, I use the code
``` r
set.seed(12345)
mat <- matrix(runif(16), ncol = 4)
corrplot(cor(mat))
box(lwd = 10)
```

at **v0.79**, the code gives the following plot:
![rplot04](https://user-images.githubusercontent.com/14980050/31830676-863ea170-b5f3-11e7-9fd8-21f85a23cf5a.png)

and at **v0.82 or higher**, the result is 
![rplot05](https://user-images.githubusercontent.com/14980050/31830761-d1b6a45e-b5f3-11e7-9cd9-f19de525ed66.png)

In fact, I have found that the problem was caused by commit 4a7ca4d

**Comment by vsimko** [comment]
There were multiple issue (#10, #96, #94, #102) that were fixed by the commit.
Unfortunately, the solution is not optimal.
However, till we find a better way, I think it is better to leave some white space, which can be automatically cropped, than to cut pieces from labels as it was in previous versions of corrplot.

Contributions are welcomed!

**Comment by vsimko** [comment]
A workaround for automated cropping using imagemagick:
```sh
# assuming you saved your plot as Rplot.png
$ convert Rplot.png -trim -bordercolor White +repage Rplot-cropped.png
```

Example:
![image](https://user-images.githubusercontent.com/7080773/31832068-e5afec3c-b5c5-11e7-8226-a89ce8f0cf7b.png)

**Comment by jinzhen-lin** [comment]
Thank you for your solution.
But I think it is better for me to degrade to v0.79  temporarily since I don't affect by those issues.

**Comment by jinzhen-lin** [comment]
I notice that you try to fix this issue. But your work causes a new problem in `corrplot.mixed`. (exactly, causes a problem in `corrplot` when the `type != "full"`): the plot may be cut off.

![rplot](https://user-images.githubusercontent.com/14980050/31853266-5a114740-b6b8-11e7-9a3e-ab21ca5f5e62.png)

Now I think I have found a good way to solve the issue and the new problem
``` r
xlim <- c(
  m1 - 0.5 - laboffset -
    xlabwidth * (grepl("l", tl.pos) | grepl("d", tl.pos)),
  m2 + 0.5 + mm * cl.ratio * (cl.pos == "r") +
    xlabwidth * abs(cos(tl.srt * pi / 180)) * grepl("d", tl.pos)
) + c(-0.35, 0.15) +
  c(-1,0) * grepl("l", tl.pos) * (type != "full") # margin between text and grid

ylim <- c(
  n1 - 0.5 - nn * cl.ratio * (cl.pos == "b") - laboffset,
  n2 + 0.5 + laboffset +
    ylabwidth * abs(sin(tl.srt * pi / 180)) * grepl("t", tl.pos)
) +
  c(-0.15, 0) +
  c(0, -1) * (type == "upper" && tl.pos != "n") + # nasty hack
  c(0,1) * grepl("d", tl.pos) * (type != "full") # margin between text and grid
```

That is, I change `c(-1,0) * grepl("l", tl.pos)` to `c(-1,0) * grepl("l", tl.pos) * (type != "full")`

**Comment by taiyun** [comment]
It's OK on my RStudio：
```
corrplot.mixed(cor(mtcars))
```
BTW, do you have wechat？ My id is cloud_wei~

**Comment by vsimko** [comment]
As I said, the code relates to multiple issues (#10, #96, #94, #102). Thus be **VERY CAREFUL** when changing the code and **EVEN MORE CAREFUL** when pushing it to git. We don't have any visual unit tests implemented at the moment and therefore all changes like this one need to be inspected manually. 

Maybe it is a good idea to create a single file that would render all problematic corner cases for easier visual inspection.

**Comment by taiyun** [comment]
@vsimko I checked these issues, there is no problem.
