### ISSUE TITLE
background color of the whole plot and the grid

### ISSUE THREAD

**Issue by jinzhen-lin** [taiyun/corrplot#116]
[Line 529 of corrplot.R](https://github.com/taiyun/corrplot/blob/5c308e6c8be53d1e469d316280670b7ebdf364e0/R/corrplot.R#L529) force the background color of the whole plot to be white.
                         
``` r
oldpar <- par(mar = mar, bg = "white")
```

In most cases, white is good. But sometimes, for the purpose of presentation, I may want the background color to be other color (for example, transparent) to fit the background color of slides. The `bg` parameter of `corrplot` can only change the background color of the grid. 

Besides, it is impossible to change the background color of grid in `corrplot.mixed`.

So, I think it is better to add the feature to change the background color of the whole plot in `corrplot` and the background color of the grid in `corrplot.mixed` if possible.

**Comment by taiyun** [comment]
It's old par to restore.
 
You can find `bg` and examples from document. 

```
corrplot(cor(mtcars), bg='yellow')
```

**Comment by jinzhen-lin** [comment]
The result of your code is 

![rplot](https://user-images.githubusercontent.com/14980050/31849078-224abb5a-b66f-11e7-9f68-3e2dea857cca.png)
 
But exactly, I want something like 

![rplot01](https://user-images.githubusercontent.com/14980050/31849084-3a36d7ee-b66f-11e7-885f-f1713e2d99a5.png)

**Comment by jinzhen-lin** [comment]
But when I use, the background color is white, not transparent. 

Besides, I use the following code

``` r
par(bg = "yellow")
corrplot(cor(mtcars))
```

The output plot is

 
![rplot02](https://user-images.githubusercontent.com/14980050/31849186-f6878334-b670-11e7-85b2-da77398c4724.png)

That is, `par(bg = "yellow")` is invalid in `corrplot`

**Comment by taiyun** [comment]
Pease try the latest version on GitHub. @jinzhen-lin

**Comment by jinzhen-lin** [comment]
Thank you very much. Now I can use `par(bg = "xxxx")` to change the background color of the whole plot.

**Comment by yulyatko** [comment]
Hi! Is there any way to change only a subset of grid to a different background color? for example to highlight one line in the grid?
