### ISSUE TITLE
Problems rendering longer labels with type="upper"

### ISSUE THREAD

**Issue by NickUK** [taiyun/corrplot#133]
As you can see with this example, the column name is truncated when using the type="upper"

```r
library(corrplot)

tmp <- cor(mtcars)
colnames(tmp)[1] <- "Miles per gallon"
corrplot(tmp, type="lower")
```

![image](https://user-images.githubusercontent.com/6517730/42651311-f3ccc224-8606-11e8-9c03-b1033db6584a.png)

This was tested in corrplot_0.84.

**Comment by cowlumbus** [comment]
statnmap has a solution:

https://github.com/taiyun/corrplot/issues/10#issuecomment-258388449
