### ISSUE TITLE
Changing range of colors

### ISSUE THREAD

**Issue by CodeInTheSkies** [taiyun/corrplot#145]
Hi there,
I am facing the same problem as #122, and have been struggling with this otherwise great package!  I do want to use this package, but also have control over the displayed range and colors.  Would have been nice if the authors had considered this feature!

Are there any work-arounds to properly limit the correlation range to anything other than [-1,1] and also map to the full range of specified colors?

Thanks!

**Comment by taiyun** [comment]
I will add `col_assign` parameter in next version. It will alow users specify the intervals of assigning colors.
