### ISSUE TITLE
Feature request: Speedup of cor.mtest()

### ISSUE THREAD

**Issue by sdittmar** [taiyun/corrplot#156]
The function `cor.mtest()` is a very useful function, but for larger datasets it can be rather slow.
Since the function is not much more than two 'for loops' it should not be too difficult for a skilled programmer to migrate it to C/C++ and speed it up. Unfortunately, I lack the skills to do that. May I suggest it as a feature request?

**Comment by taiyun** [comment]
corrplot focus on plot small correlation matrix.
