### ISSUE TITLE
full_col=TRUE causes color/legend mismatch

### ISSUE THREAD

**Issue by mkanai** [taiyun/corrplot#157]
Hi, I found a bug due to a new default argument `full_col=TRUE` which causes color/legend mismatch.

```
# CRAN version, v0.84, works
install.packages("corrplot")
library(corrplot)
corrplot(cor(mtcars)/2)
```
<img src="https://user-images.githubusercontent.com/121819/97138107-ca4dde00-172d-11eb-96eb-a26843c2ce3e.png" width="600">

```
# GitHub version, v0.85, doesn't work
devtools::install_github("taiyun/corrplot")
library(corrplot)
corrplot(cor(mtcars)/2)
```
<img src="https://user-images.githubusercontent.com/121819/97138193-fec19a00-172d-11eb-99ed-822e7c4bc38f.png" width="600">

I think the correct default behavior is either the following A) or B). Although I found a good use case in #122, I'd like to suggest making `full_col=FALSE` as a default for backward compatibility. It might be also a good idea to warn users when they set `full_col=TRUE` but didn't specify `cl.lim` or `is.corr=FALSE`.

```
# A) correct 0-1 color and legend
corrplot(cor(mtcars)/2, full_col=FALSE)
```
<img src="https://user-images.githubusercontent.com/121819/97138226-139e2d80-172e-11eb-872b-bff7e0881f7e.png" width="600">

```
# B) correct full-range color and legend 
corrplot(cor(mtcars)/2, full_col=TRUE, is.corr=FALSE)
```
<img src="https://user-images.githubusercontent.com/121819/97138246-20bb1c80-172e-11eb-9721-eaad4bebd80f.png" width="600">

**Comment by taiyun** [comment]
Yes, I have removed `full_col` just now.

For #122, I will find a better way to solve it.

**Comment by mkanai** [comment]
Great, thank you!

**Comment by taiyun** [comment]
@mkanai on CRAN now. corrplot v0.88
