### ISSUE TITLE
Checks for [-1; 1] interval are too strict

### ISSUE THREAD

**Issue by nalimilan** [taiyun/corrplot#16]
When computing a weighted correlation matrix with `wt.cor(.., cor=TRUE)$cor`, diagonal correlations can be slightly above 1 or slightly below -1, but `corrplot` raises an error which is likely to confuse users since the printed values are either 1 or -1. The checks could be made a bit more tolerant by checking for `x <= 1 + 2 * .Machine$double.eps` and `x >= -1 - 2 * .Machine$double.eps` (which worked in my case, but one could be a bit more tolerant...).

**Comment by taiyun** [comment]
The current version is
```
if (min(corr) < -1 - .Machine$double.eps || max(corr) > 
      1 + .Machine$double.eps)
```

Does it work in your case?

**Comment by nalimilan** [comment]
Since the current code uses `<` instead of `<=`, it it equivalent to `<= 1`, which is too strict for my use case. Using `<=` and `=>`, as well as the `2*` part was needed for me.

**Comment by taiyun** [comment]
It is correct using `<`, you can see the code.

```
if(min(corr) < -1 - .Machine$double.eps ^ (3/4) || max(corr) > 1 + .Machine$double.eps ^ (3/4) ){
		stop("The matrix is not in [-1, 1]!")
	} 
```

**Comment by nalimilan** [comment]
Looks fine, thanks!
