### ISSUE TITLE
Keep order of dataset

### ISSUE THREAD

**Issue by KistinaMohamed** [taiyun/corrplot#172]
Hi,

Is there a way to get corrplot to plot data according to the same order in corrMatrix? I can't seem to make out the random pattern that comes out when running corrplot of my corrMatrix.

Many thanks.

**Comment by taiyun** [comment]
corrplot keeps order of corrMatrix by default. For details, see `order` parameter:

```
order, Character, the ordering method of the correlation matrix.

"original" for original order (default).
"AOE" for the angular order of the eigenvectors.
"FPC" for the first principal component order.
"hclust" for the hierarchical clustering order.
"alphabet" for alphabetical order.
```
