### ISSUE TITLE
title position and pie corrplot background circle 

### ISSUE THREAD

**Issue by zhilongjia** [taiyun/corrplot#18]
1. When `type="lower"`, is it possible to put title in upper section, instead of top? Sometimes, the title is far from the figure itself.
2. Make the circle perimeter nonvisual (see figure) or add a parameter.
   ![corrplot](https://cloud.githubusercontent.com/assets/1230436/11446713/c2b55678-9532-11e5-820e-c1d87776ebed.png)

line 241 in corrplot.R. 

original: 

```r
symbols(Pos, add = TRUE, inches = FALSE, circles = rep(0.5, len.DAT) * 0.85)
```

nonvisual circle perimeter:

```r
symbols(Pos, add = TRUE, inches = FALSE, circles = rep(0.5, len.DAT) * 0.85, fg = bg)
```

**Comment by taiyun** [comment]
Thanks.

**Comment by vsimko** [comment]
I would propose to use the existing parameter `outline` to control the border inside the pie symbol.
This would slightly change the default behavior of the function as follows:

Examples:
```r
# new default behavior
corrplot(cor(mtcars), type = "lower", method = "pie")
```
![image](https://cloud.githubusercontent.com/assets/7080773/22738848/6e7312b8-ee09-11e6-850d-84f70d916960.png)

```r
# same as the original default behavior with `outline = FALSE`
corrplot(cor(mtcars), type = "lower", method = "pie", outline = TRUE)
```
![image](https://cloud.githubusercontent.com/assets/7080773/22738895/a825811c-ee09-11e6-9ced-ddc185c57107.png)

```r
# the requested "perimeter nonvisual" version
corrplot(cor(mtcars), type = "lower", method = "pie", outline = "white")
```
![image](https://cloud.githubusercontent.com/assets/7080773/22738924/d01e893e-ee09-11e6-837e-740174e9ece1.png)

Please vote!

**Comment by vsimko** [comment]
merged to master
