### ISSUE TITLE
Not possible to remove background color for insignificant results in the newest version (0.90)

### ISSUE THREAD

**Issue by anja-elaine** [taiyun/corrplot#221]
Dear Corrplot team,

Huge fan of the package. However, I have run into an issue with the newest version of corrplot (0.90).
It was previously possible to have a white background for insignificant results, while still showing the correlation coefficients. 
In the new version, I am unable to do this, and not sure if it is a bug in the updated version as my code has not changed. 
Following this example: http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram with the new version does not work - but with older versions it does. 
For now, I have solved my issue by installing an older version, but that hardly seems like a good plan in the end. 

Please let me know how I best can help, I have even made a post on StackOverflow with a (hopefully) reproducible example, please see here: https://stackoverflow.com/questions/68316664/potentiel-bug-in-corrplot-correlation-coefficients-not-visable-when-insig-bl. 

Kind regards,
Anja Sørensen

**Comment by taiyun** [comment]
Dear anja,

This a feature suggested by some users. However, it doesn't seem to meet your requirements ​:(

You can show all coefficients with 2 extra lines of code, like this:

```
M<-cor(mtcars)
corrplot(M, method="color", 
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
) -> p
p = r$corrPos
text(p$x, p$y, round(p$corr,2), font = 2)
```

**Comment by anja-elaine** [comment]
Dear Taiyun and corrplot

Thank you very much for your fast reply.
I will try out the extra lines.

Thank you once again.

All the best,
Anja


Fra: Taiyun ***@***.***>
Sendt: 21. juli 2021 15:24
Til: taiyun/corrplot ***@***.***>
Cc: Anja Elaine Sørensen ***@***.***>; Author ***@***.***>
Emne: Re: [taiyun/corrplot] Not possible to remove background color for insignificant results in the newest version (0.90) (#221)


Dear anja,

This a feature suggested by some users. However, it doesn't seem to meet your requirements ​:(

You can show all coefficients with 2 extra lines of code, like this:

M<-cor(mtcars)



corrplot(M, method="color",



         type="upper", order="hclust",



         addCoef.col = "black", # Add coefficient of correlation



         tl.col="black", tl.srt=45, #Text label color and rotation



         # Combine with significance



         p.mat = p.mat, sig.level = 0.01, insig = "blank",



         # hide correlation coefficient on the principal diagonal



         diag=FALSE



) -> p



p = r$corrPos



text(p$x, p$y, round(p$corr,2), font = 2)
