### ISSUE TITLE
Can't install corrplot

### ISSUE THREAD

**Issue by cmazier** [taiyun/corrplot#224]
Hello,

I tried to install this corrplot version because I have NA in my data. 

I did :  devtools::install_github('taiyun/corrplot', build_vignettes = TRUE) but I had this error message:

"Downloading GitHub repo taiyun/corrplot@HEAD
Erreur : Failed to install 'corrplot' from GitHub:
  create process 'C:/PROGRA~1/R/R-40~1.3/bin/x64/Rcmd.exe' (system error 267, Nom de répertoire non valide.
) @win/processx.c:1040 (processx_exec)
De plus : There were 50 or more warnings (use warnings() to see the first 50)"

I think it is because I have an accent in the access path but I can't remove it. Have you another solution to install this?

**Comment by taiyun** [comment]
You can install corrplot from CRAN.

```
install.packages('corrplot')
```
