### ISSUE TITLE
Adjusting color bounds v.90

### ISSUE THREAD

**Issue by Esterng93** [taiyun/corrplot#225]
Hello, I'm having problems adjusting the color-legend bounds of the correlation matrix using col.lim() and is.corr as previously suggested. I am trying to shrink the bounds of the correlation to show low correlations (.1-.3) more clearly. In v. .90 neither of those arguments changes the correlation plot and when using col.lim() I get this error: "color limits should cover matrix", even when using is.corr = FALSE. Only using is.corr = FALSE doesn't have any effect. Any ideas? Thank you! Below is an example of  what I am doing.

corrplot::corrplot(dfcor, method="number", order="hclust", tl.cex = .8,tl.col= "black", cl.cex = .3, is.corr=FALSE)

**Comment by taiyun** [comment]
Please check your data. Make sure all values are in `(.1-.3)`.
