### ISSUE TITLE
Re-opening the issue of col.lim

### ISSUE THREAD

**Issue by bixiou** [taiyun/corrplot#231]
It turns out that the issue [228](https://github.com/taiyun/corrplot/issues/228) was closed without being solved. Indeed, no code was provided to obtain the expected result. I am thus re-opening the issue.

**Comment by taiyun** [comment]
It's a bug. I reopen #228 . Thanks.

**Comment by taiyun** [comment]
I just fixed it on Github version. And I will submit it to CRAN after more work in this month.
