### ISSUE TITLE
How to add group information in the picture?

### ISSUE THREAD

**Issue by liufuyan2016** [taiyun/corrplot#241]
I have three group , and each group have 10 sample ,and I want to label the group name in the picture.
Could you help me?
Thank you!

**Comment by taiyun** [comment]
How label them? Can you give some details?

**Comment by liufuyan2016** [comment]
see example:
![6a9a46ee724380f2f785d11421fefc1](https://user-images.githubusercontent.com/23466455/141707121-5b23b559-3498-457f-a40d-2950b4ed270b.jpg)

**Comment by taiyun** [comment]
Hi, corrplot can add rectangles but can't label the group name in the picture.
