### ISSUE TITLE
How to reverse the order of the diverging color

### ISSUE THREAD

**Issue by JennyWeng** [taiyun/corrplot#242]
Hi,
Thanks for the fantastic package. It's quite easy to use! Maybe a naive question, but can we reverse the order of the diverging color? For instance, for the "RdBu", to put red on value 1 and blue on value -1. Thank you very much!

Best,
Jenny

**Comment by taiyun** [comment]
example

```
M = cor(mtcars)
corrplot(M, order = 'AOE', col = COL2('RdBu'))
corrplot(M, order = 'AOE', col = rev(COL2('RdBu')))
```
