### ISSUE TITLE
Significant Asterisk in corrplot.Mixed

### ISSUE THREAD

**Issue by BB1464** [taiyun/corrplot#243]
Good evening Dear all,
    Please is there any way in which I can add significant asterisk on my corrplot using the corrplot.mixed function ? Using the mtcars dataset  below. Thank you for your anticipated response 

library(corrplot)
T <- cor.mtest(mtcars)
M <- cor(mtcars)
corrplot.mixed(cor=M,p.mat=T$p))

**Comment by taiyun** [comment]
```
corrplot.mixed(cor=M,p.mat=T$p,
  sig.level = c(0.001, 0.01, 0.05), pch.cex = 0.9,
  insig = 'label_sig', pch.col = 'grey20')
```

**Comment by BB1464** [comment]
Thank you for your reply @taiyun, please  how can I remove the significant asterisk for the upper triangle in which I used shapes?
