### ISSUE TITLE
addgrid in mixed plot

### ISSUE THREAD

**Issue by ZoomMan91** [taiyun/corrplot#247]
Hi,
There was the issue [42](https://github.com/taiyun/corrplot/issues/42) here, but about regular corrplot.
I will use same matrix as an example.
`M <- matrix(runif(2500, 0.5, 1), nrow = 50)`

If one would like to remove grid in corrplot.mixed he/she should use addgrid.col = NA (according to docs).
But It has no real reflection.
`corrplot.mixed(M,addgrid.col = NA)`

![image](https://user-images.githubusercontent.com/25316716/152127806-53b4b135-832d-48b6-80b0-7d504e027f14.png)

or 
`corrplot.mixed(M,addgrid.col = 'green')`

![image](https://user-images.githubusercontent.com/25316716/152127952-9f7c0712-05e0-4e37-a647-a75b0b4342c7.png)

Side question. Is there is any option not to use grid on the lower part, but keep the frame?
Thanks.

**Comment by taiyun** [comment]
Thanks.

`addgrid.col ` works well in `corrplot()` but does not work in `corrplot.mixed()`. I will fix this bug soon.

**Comment by taiyun** [comment]
Fixed now.

**Comment by ZoomMan91** [comment]
Thanks! Works perfect!
