### ISSUE TITLE
R dependency is >=4.1.0

### ISSUE THREAD

**Issue by MichaelChirico** [taiyun/corrplot#248]
Hi, the examples for `corrRect()` induce a dependency on R >= 4.1.0.

Unfortunately, it's impossible to branch away usage of `|>` depending on the R version, because `|>` is not actually a function, but is interpreted by the parser. So the parser itself needs to know of `|>` in order for the example to parse, otherwise we get:

```
> if(getRversion() >= '4.1.0') {
+   corrplot(M, order = 'AOE') |> corrRect(namesMat = r)
Error: unexpected '>' in:
```

Please either add an explicit R version dependency or remove the examples (or put them in comments)

**Comment by taiyun** [comment]
I will put them in comments.
