### ISSUE TITLE
Control the square size independently

### ISSUE THREAD

**Issue by wym0072003** [taiyun/corrplot#253]
Hi Taiyun,

Thanks for the great tool!

I will generate a heatmap by integrating correlation values and P values using 'corrplot(M, method = 'square')'.
I found that the square size is consistent with the color scale. How can I control either of the square sizes independently? 
For example, I use different square sizes to indicate the correlation and meanwhile use the color gradient to indicate different P-value.
Here is an example of plot (DOI: 10.1126/science.aap8757, this is the paper where it comes). 
![a nice heatmap](https://user-images.githubusercontent.com/12169843/170197219-002be268-9cb3-48eb-b384-5d5b992e8860.jpg)

Thanks!

Best regards

Yiming

**Comment by taiyun** [comment]
Yes, the square size is consistent with the color scale. You can't set it independently.

**Comment by ivokwee** [comment]
would be nice to be able to do this though. Can you consider to implement it? So color for the correlation and size for the p-value (or actually 1-p or -log10 or something increasing for smaller p)
