### ISSUE TITLE
Specifying Corrplot Scale Breaks

### ISSUE THREAD

**Issue by Suraj-Bansal** [taiyun/corrplot#254]
Hi Taiyun, 

Thanks for an amazing package — I use corrplot regularly!
I cannot find the parameter to specify the scale breaks in my plot (in ggplot I usually use scale_fill_continuous). Here is my plot. I am looking to only show the breaks: 0, 0.01, 0.02, 0.03, 0.04, 0.05. If you could help me resolve this, I would greatly appreciate it!

![image](https://user-images.githubusercontent.com/49488421/176472960-45f5b9c2-91aa-4d46-bff2-e6972d818b48.png)

**Comment by taiyun** [comment]
You can try like this:
```
corrplot(M,  col = COL1('Blues', 5))
```

**Comment by taiyun** [comment]
Or

```
corrplot(M,  cl.length = 5)
```
