### ISSUE TITLE
specifying the color range

### ISSUE THREAD

**Issue by imilenkovic** [taiyun/corrplot#255]
Hello,

I was wondering if it would be possible to specify the range in which a color gradient will be applied? 
For example:
![image](https://user-images.githubusercontent.com/51703618/183949253-5765f666-9f9a-43f4-aaff-47ab83f46501.png)

in this plot the range is from 1 to -1, but I would like to only have it eg. from 1 to -0.15, so that the values around 0 are bright yellow and values around 1 are brown?

Thank you.

**Comment by taiyun** [comment]
You can set `col.lim`.

Examples:  https://taiyun.github.io/corrplot/

**Comment by imilenkovic** [comment]
Hello,

When I set col.lim, the colour distribution stays the same.

```
corrplot(cor(merged2),        # Correlation matrix
         method = "shade", # Correlation plot method
         type = "full",    # Correlation plot style (also "upper" and "lower")
         diag = TRUE,      # If TRUE (default), adds the diagonal
         tl.col = "black", # Labels color
         bg = "white",     # Background color
         title = "",       # Main title
         col.lim = c(-0.15,1),
         is.corr = FALSE,
         COL1(sequential = c("YlOrBr")))        # Color palette
```
![image](https://user-images.githubusercontent.com/51703618/186949510-2efc1453-4fe8-4ab6-987e-db548dae78e2.png)


When changing is.corr to TRUE, it's still the same:

```
corrplot(cor(merged2),        # Correlation matrix
         method = "shade", # Correlation plot method
         type = "full",    # Correlation plot style (also "upper" and "lower")
         diag = TRUE,      # If TRUE (default), adds the diagonal
         tl.col = "black", # Labels color
         bg = "white",     # Background color
         title = "",       # Main title
         col.lim = c(-0.15,1),
         is.corr = TRUE,
         COL1(sequential = c("YlOrBr")))        # Color palette
```
![image](https://user-images.githubusercontent.com/51703618/186949700-b59a6421-4c61-4993-b63f-74a659eb8947.png)

I assume that I would have to use diverging colours here, but the same colour palette doesn't exist with diverging colours. I already made many other plots with this colour scheme so I would prefer to stick to the same colours if at all possible. Thanks!

**Comment by taiyun** [comment]
Please update the new version v0.93 from Github. And set `ignoreSign = TRUE`.

**Comment by imilenkovic** [comment]
Hello,

I updated the package and ran the following:

````
corrplot(cor(merged2),        # Correlation matrix
         ignoreSign = TRUE,
         method = "shade", # Correlation plot method
         type = "full",    # Correlation plot style (also "upper" and "lower")
         diag = TRUE,      # If TRUE (default), adds the diagonal
         tl.col = "black", # Labels color
         bg = "white",     # Background color
         title = "",       # Main title
         col.lim = c(-0.2,1),
         is.corr = FALSE,
         COL1(sequential = c("YlOrBr")))   
````

and got the following warning

`Warning message:
In corrplot(cor(merged2), ignoreSign = TRUE, method = "shade", type = "full",  :
  col.lim interval not suitable to the matrix`

The plot now looks like this:

![image](https://user-images.githubusercontent.com/51703618/187161686-32f182fd-c4fa-49d6-8d86-2add4099390c.png)

**Comment by taiyun** [comment]
> Please update the new version v0.93 from Github. And set `ignoreSign = TRUE`.

`ignoreSign = TRUE` is very easy to misunderstood.

I rename it, please set `transKeepSign = FALSE` after updating.
