### ISSUE TITLE
corrRect does not draw full rect at the y limits

### ISSUE THREAD

**Issue by Famondir** [taiyun/corrplot#259]
Hello there,
I just started using corrPlot and tried to draw some custom rects with namesMat. Here my code:

```
M <- data %>% select(starts_with("Anwendung"), Selbstwirksamkeit, ExtMotiv_Ergebnis, IntrinsischeMotivation, Interesse) %>% 
  select(-Anwendung_Anzahl) %>% 
  mutate_all(as.double) %>% 
  setNames(str_replace(names(.), "_",  "\n")) %>% 
  cor(method = "kendall", use="pairwise.complete.obs")
 
corrplot.mixed(M, upper = 'shade', order = 'AOE', tl.cex = .7) %>% 
  corrRect(namesMat = c("ExtMotiv\nErgebnis", "Anwendung\nAbgestimmt", "Interesse", "Anwendung\nModulbedeutung"))
```

![image](https://user-images.githubusercontent.com/43599267/188826682-afc325d5-aacf-41b7-9af0-09f451ac7abb.png)

The problem is that the rect is not drawed completely on the lower border. Same happens on the top border:

```
corrplot.mixed(M, upper = 'shade', order = 'AOE', tl.cex = .7) %>% 
  corrRect(namesMat = c("Anwendung\nAbgestimmt", "ExtMotiv\nErgebnis", "Anwendung\nModulbedeutung", "Interesse"))
```

![image](https://user-images.githubusercontent.com/43599267/188827862-c9d3ac48-5adf-4679-87d6-2534bb7a4a2e.png)

I use R 4.2.1 on Windows 10 build 19042.1889.

I hope you can help me out here.

**Comment by taiyun** [comment]
This is due to the resolution.

You can save it as a pdf file.
