### ISSUE TITLE
number.digits argument does not display trailing zeros

### ISSUE THREAD

**Issue by the-mad-statter** [taiyun/corrplot#275]
The correlation between drat and gear is listed as 0.7 and not 0.70.

``` r
library(dplyr)
library(corrplot)

M <- mtcars |> select(gear, am, drat) |> cor()

corrplot(
  M, 
  type = "lower", 
  diag = FALSE, 
  addCoef.col = "black", 
  number.digits = 2
)
```

![](https://i.imgur.com/notGImr.png)

<sup>Created on 2024-04-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by taiyun** [comment]
Thanks
