### ISSUE TITLE
Version 0.94 is not assigning significant ocurrences correctly

### ISSUE THREAD

**Issue by brenoliisboa** [taiyun/corrplot#279]
![Captura de tela 2024-09-14 014559](https://github.com/user-attachments/assets/88183a49-4c29-4977-a5b4-bc3aa101de29)
![Captura de tela 2024-09-14 014527](https://github.com/user-attachments/assets/445d6422-6cb0-4d3e-a360-9c890535b20c)

As written in the title, v.0.94 is having this issue (top image). Version 0.92 plots correctly p value under 0.05 (bottom image).
[..]
method = c("color"),
         tl.col = "black",
         order = "hclust",
         p.mat = p_value_matrix, 
         sig.level = 0.05, 
         insig = "label_sig"
         [..]

**Comment by taiyun** [comment]
Can you show your data and code？

**Comment by david-priest** [comment]
I'm getting the same issue.  If `order = "original"`, then the significances and correlations line up, but if `order = "hclust"`, then the correlations and significances no longer align.

**Comment by taiyun** [comment]
Many Thanks. I  fixed it and will submit new version v0.95 to CRAN soon.
