### ISSUE TITLE
"Corrplot" Install Server Down

### ISSUE THREAD

**Issue by brigidojunior** [taiyun/corrplot#283]
Hey guys! Hope to find you well!

I'm trying to install "corrplot" package but the following error occurs. It seems that the instalation server (https://cran.wustl.edu/src/contrib) is down. Can you help me with that?

Warning in install.packages :
  não é possível acessar o índice para o repositório https://cran.wustl.edu/src/contrib:
  não foi possível abrir a URL 'https://cran.wustl.edu/src/contrib/PACKAGES'
Warning in install.packages :
  pacote ‘corrplot’ não está disponível for this version of R

Uma versão deste pacote para a sua versão do R pode estar disponível em outro lugar,
veja as ideias em
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  não é possível acessar o índice para o repositório https://cran.wustl.edu/bin/windows/contrib/4.4:
  não foi possível abrir a URL 'https://cran.wustl.edu/bin/windows/contrib/4.4/PACKAGES'

**Comment by taiyun** [comment]
Try

```
devtools::install_github('taiyun/corrplot', build_vignettes = TRUE)
```
