### ISSUE TITLE
Size and number of decimals of coefficients of correlation 

### ISSUE THREAD

**Issue by ksahlin** [taiyun/corrplot#36]
Hi,

Thanks for the great library. I have a correlation plot with 46 variables. When plotting with method="number", the size of the number exceeds the size of the square. Is it possible to change to font size of the correlations of coefficients? Also, is it possible to change the number of decimals? 

If not, this would be two great features!

Best,
Kristoffer

**Comment by taiyun** [comment]
First question, you can try this:
```
pdf(width=20,height=20)
## draw corrplot here
dev.off()
```

**Comment by taiyun** [comment]
Second question, download the development version of the package and use `number.digits` parameter:

```
install.packages("devtools")
devtools::install_github("taiyun/corrplot")
corrplot(cor(mtcars), method='number')
corrplot(cor(mtcars), method='number',addCoefasPercent = TRUE)
corrplot(cor(mtcars), method='number', number.digits = 1)
```

**Comment by vsimko** [comment]
I think, this question has been answered => closing.
