### ISSUE TITLE
Large dataset = diagonal not straight

### ISSUE THREAD

**Issue by gdkrmr** [taiyun/corrplot#38]
i am trying to plot the correlations of a large dataset (~1300 variables) and saw that the diagonal doesn't appear straight. I was not able to reproduce this using random matrices, maybe you can give me some hint on how to debug this:
![corrplot](https://cloud.githubusercontent.com/assets/12512930/13664271/9494c876-e6a6-11e5-9f9c-41e59e1a6246.png)

here the same correlation matrix with `image`:
![image](https://cloud.githubusercontent.com/assets/12512930/13664272/94b5b57c-e6a6-11e5-9ee3-bcf3977427db.png)

**Comment by vsimko** [comment]
@gdkrmr Could you at least provide some code-snippet that renders the same plot using random data.

**Comment by gdkrmr** [comment]
as I said above, I was not able to reproduce it with random data. If you give me some hint where to look and/or find some extra time, I will take another look at it.

**Comment by vsimko** [comment]
I understand, but it would help me if I knew the exact function call (what parameters you used etc.)
If you cannot reproduce it with random data, would it be possible to give me the original matrix ?

**Comment by taiyun** [comment]
Can you try the package on github, version 0.74?

I guess that the version in your example is 0.73 on CRAN.

**Comment by gdkrmr** [comment]
that is the call:
```R
corrplot(m, addgrid.col = NA, outline = F, cl.pos = 'n', tl.pos = 'n', order = 'AOE')
```
`any(m>1)` is `FALSE`
and I could not make the error go away changing any of the above parameters, `addgrid.col` and `outline` are necessary, because else the results is just a gray/black plot.

**Comment by gdkrmr** [comment]
i just figured out that the diagonal is straight, if I confine my data to `[-1+1e-10, 1-1e-10]`.

**Comment by vsimko** [comment]
For the record, I tried this without reproducing the error:
```r
M <- matrix(runif(90000, -1+1e-40, 1-1e-10), nrow=300)
diag(M) <- 0
corrplot(M, method = "color", na.label = "square", addgrid.col = NA, tl.pos = "n")
```
![image](https://cloud.githubusercontent.com/assets/7080773/13997732/c5ca9276-f133-11e5-8c1a-4a1f43398516.png)

**Comment by gdkrmr** [comment]
great, I cannot reproduce it any more!
