### ISSUE TITLE
Allow separate colors for X-label and Y-label

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#41]
I saw that we have a non-mergeable pull request from @zhilongjia who suggested to add separate parameters `tl.x.col` and `tl.y.col` instead of the current `tl.col`. This looks like a reasonable feature.
**However, it would also break the current API.**

Therefore, I would like to suggest to rather keep the `tl.col` parameter that can either contain the color name as a string e.g. "red" or separate colors as a pair, e.g `c("red", "blue")` - red for X, blue for Y label.

Any suggestions ?

**Comment by taiyun** [comment]
Yes. We should not break the current API. 

Add, I don't think that it's a necessary feature.

**Comment by vsimko** [comment]
Ok, closing the feature request then.

**Comment by scottkall** [comment]
I was just looking for this feature. Will try to use the fork by @zhilongjia
