### ISSUE TITLE
NAs still causing problems ?

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#49]
@CrHvG:

> Thanks for the great package. I've installed the update, but I still get an error when running a corr matrix with NAs. When will this be available to the public? Also, why not just display "NA" rather than "?"? The value may not be in question ("?"), but may be genuinely not applicable ("NA"). Thanks.

**Comment by vsimko** [comment]
Could you elaborate more on:
- corrplot version used
- data used for plotting
- code used for plotting

**Comment by CrHvG** [comment]
packageVersion("corrplot")
[1] ‘0.73’

> M1 = M2 = cor(mtcars)
> diag(M1) = 0
> diag(M2) = NA

> # should not be the same
> corrplot(M1) 
> corrplot(M2) 
Error in if (min(corr) < -1 - .Machine$double.eps || max(corr) > 1 + .Machine$double.eps) { : 
  missing value where TRUE/FALSE needed

**Comment by vsimko** [comment]
This has already been  fixed in issues #46
```r
packageVersion("corrplot") # version I'm currently using
[1] ‘0.75’
```

**Comment by CrHvG** [comment]
Thanks!

Sorry for the bother, but when will the newest version (0.75) be up on CRAN? Seems 0.73 is up there now.

Cheers,

Chris

**Comment by vsimko** [comment]
@taiyun is responsible for CRAN deployment (see also issue #33)

**Comment by CrHvG** [comment]
Hi Viliam,

Thanks again for your help. It seems the version 0.73 is still up. Is there any way you could give me the corrected function (which allows NA values) for me to use in the meantime?

Many thanks,

Chris

**Comment by vsimko** [comment]
Hi Chris,
it's actually quite simple. To install the latest version from github, just run the following commands inside your RStudio.

```r
install.packages("devtools")
devtools::install_github("taiyun/corrplot")
```

**Comment by CrHvG** [comment]
Thanks. That worked, except it still plots the "NA"s as "?"s. (using same test code as above)

**Comment by vsimko** [comment]
NAs should be plotted as "?" by default.
The following example shows the difference between plotting zeroes (shows empty cell) and NAs (shows "?").

```r
M1 = M2 = cor(mtcars)
diag(M1) = 0 # should be rendered as empty cells
diag(M2) = NA # should be rendered as "?" symbols
```

```r
corrplot(M1)
```
![image](https://cloud.githubusercontent.com/assets/7080773/14084821/f56c81dc-f51c-11e5-97d7-665c936d590b.png)

```r
corrplot(M2) 
```
![image](https://cloud.githubusercontent.com/assets/7080773/14084833/0122ff56-f51d-11e5-9283-fcba11f75326.png)

**Comment by CrHvG** [comment]
Thanks, as per my original comment, there are times when "NA"s should be represented as "NA" simply because any value in that cell would not be applicable, and not as "?", which seems to indicate there is a question. In my case, there is no question, just cells (in the correlation matrix) for which any value would not be applicable. To conclude, can the matrix represent "NA" as "NA" and not "?"?

**Comment by vsimko** [comment]
There is a paramter `na.label`. However, it currently only allows for a single character (default "?").
You might use the following:
```r
corrplot(M2, na.label = "N")
```
![image](https://cloud.githubusercontent.com/assets/7080773/14085103/3d7f3e8c-f51e-11e5-98c7-40a6999abe2e.png)

In later version, we might also add support for multiple characters:
```r
corrplot(M2, na.label = "NA", number.cex = .7) # this currently does not work !
```
![image](https://cloud.githubusercontent.com/assets/7080773/14085224/ee552258-f51e-11e5-84c6-ab2d206af6ea.png)

**Comment by CrHvG** [comment]
Thanks again, I look forward to the later version that would support "NA" as two characters

**Comment by vsimko** [comment]
See issue #55
