### ISSUE TITLE
Is there a way to print only the top labels?

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#51]
I found this question on stackoverflow:
http://stackoverflow.com/questions/30207260/corrplot-label-printing

```r
df <- data.frame(
    x1 = rnorm(20), x2 = rnorm(20), x3 = rnorm(20), x4 = rnorm(20),
    x5 = rnorm(20), x6 = rnorm(20), x7 = rnorm(20), x8 = rnorm(20),
    x9 = rnorm(20), x10 = rnorm(20), x11 = rnorm(20), x12 = rnorm(20))
cormatx <- cor(df)
corrplot(cormatx, method="color")
```

> Now I can alter the position of the labels by adding tl.pos=... which, according to the package manual, only takes "lt", "ld", "td", "d" or "n" as arguments. These are "left and top", "left and diagonal", "top and diagonal", "diagonal" and "NULL" respectively. (To my knowledge all the arguments involving the "diagonal" option won't even work with method="color").
> 
> Is there a way to print only the top labels. I tried tl.pos="t", without any luck. I think that argument just isn't supported so it returned "default".

**Comment by taiyun** [comment]
It's a bad idea that only print the top labels.

**Comment by vsimko** [comment]
I actually posted an answer to the stackoverflow question which is a bit of a hack.
See this link: http://stackoverflow.com/questions/30207260/corrplot-label-printing/36893890#36893890
