### ISSUE TITLE
Second vignette from a blog

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#52]
I found the following blog post:
[Visualize correlation matrix using correlogram](http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram)

It contains a very nice collection of plots that would be a nice vignette for our package.
Any opinion on this ?

**Comment by taiyun** [comment]
Our vignette contains more plots:

https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html

Maybe we should reorganize  the vignette to make it more readable.

**Comment by vsimko** [comment]
Or perhaps to split the single vignette to multiple "chapters". Vignettes should be more than just a list of plots. There should be some explanatory text around.

**Comment by taiyun** [comment]
Yes. It needs more explanatory text.

**Comment by kassambara** [comment]
Hi @vsimko,

Thank you for your work on this great R package. It's ok for me to make second vignette out of the blog post.

Best Regards,
A. KASSAMBARA,
http://www.sthda.com/english/

**Comment by vsimko** [comment]
Hi @kassambara,
are you going to create the vignette, or should I do it ?
Best regards,
Viliam

**Comment by kassambara** [comment]
Hi @vsimko ,

I will make a pull request providing the Rmd file.

Best,
Alboukadel

**Comment by vsimko** [comment]
Hi @kassambara, any progress since March ?

**Comment by vsimko** [comment]
I finally decided to merge the content of your blog post into our vignette. Thanks!
Thus the second vignette is not needed anymore.

**Comment by kassambara** [comment]
Oh great @vsimko, thank you for this lovely R package.

With regards,
/Alboukadel
