### ISSUE TITLE
add example for corrplot with NAs

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#57]
Support for NAs in corrplot has been discussed in issues #55, #49, #46 and #7.
Some code utilizing the NAs is already located in `tests/testthat/test-corrplot.R`.
However, we also need some demo code snippets and plots in examples and vignettes, i.e.
- in `vignettes/example-corrplot.R`
- in `vignettes/corrplot-intro.Rmd`

**Comment by taiyun** [comment]
added.
