### ISSUE TITLE
rounded r values

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#67]
I am trying to show the correlation r values in at least two decimal instead rounded up (e.g. 0.99 instead of 1)  as corrplot always rounded the r values.

May I ask is there any parameter in the corrplot package allowed to do so?

**Comment by jinkeanlim** [comment]
After did a lot of Googling, I came across to this old github issue #37 

The corrplot's **_number.digits_** parameter somehow allowing coefficient of correlation (r) values showed in the plot with different decimal. However, it still rounded up some r values in plot if you look at the example plot in github issue #37

It would be great if this **_number.digits_** can show exactly the desire decimal in the plot with the code `corrplot(M, method = "number", order = "AOE", number.cex = .5, number.digits = 3)`

Thanks for your time.

**Comment by jinkeanlim** [comment]
As I have mentioned in my previous comment, the _**number.digits**_ did not show exactly the desire decimal in the plot. I attached the plots and the R code here for your reference. 

`corrplot(mcor_s2s, method = "circle", type = "upper", order = "original", addCoef.col  =  "white", number.cex  =  0.8, number.digits = 2, p.mat  =  p.mat_s2s, sig.level  =  0.05, insig  =  "blank", diag = FALSE)`

`corrplot(mcor_s2s, method = "circle", type = "upper", order = "original", addCoef.col  =  "white", number.cex  =  0.8, number.digits = 3, p.mat  =  p.mat_s2s, sig.level  =  0.05, insig  =  "blank", diag = FALSE)`

![s2s_test](https://cloud.githubusercontent.com/assets/20062526/16235802/c79784a0-37de-11e6-91b6-3385928df364.gif)

If the _**number.digits = 2**_ works, the r value in the plot for 
S1:S5 should be 0.69; 
S2:S4 should be 0.60; 
S5:S6 should be 0.99

It would be great if this _**number.digits**_ parameter can show exactly the desire decimal in the plot. 

Thank you very much for your time.

**Comment by vsimko** [comment]
could you also upload the `mcor_s2s` dataset?

**Comment by vsimko** [comment]
The text labels are now computed using the `round` function as follows:
``` r
rawLabels <- (DAT - int) * ifelse(addCoefasPercent, 100, 1) / zoom
labels = round(rawLabels, number.digits)
```

I could avoid rounding as follows:
``` r
labels = rawLabels - sign(rawLabels) * (abs(rawLabels) %% 10 ^ (-number.digits))
```

@taiyun do you think it is less confusing to use the exact number of digits rather than a rounded number as suggested by @jinkeanlim ?

**Comment by taiyun** [comment]
@vsimko , round is generally better. I think @jeffzemla 's idea is much more personal.

BTW Could you please explain why

```
S1:S5 should be 0.69; not 0.70.
```

**Comment by vsimko** [comment]
I'll call it "wontfix" then

**Comment by jeffzemla** [comment]
I think you mean @jinkeanlim?

**Comment by jinkeanlim** [comment]
@vsimko the round 2 digits is fine. 

The question here is, the r values in the plot were rounded even the _**number.digits = 2**_ parameter was set. 

For example in the plot I attached,  S5:S6 should be 0.99 (in two decimal format) instead 1 when the _**number.digits = 2**_ parameter was set. That is my suggestion.  

However, three decimal will show in the plot when   the _**number.digits = 3**_ parameter was used.

**Comment by vsimko** [comment]
It may sound strange, but 0.999 rounded to 2 decimal places is actually 1.0

**Comment by jinkeanlim** [comment]
@vsimko <https://github.com/vsimko> the s2s dataset



On 22 June 2016 at 11:30, Viliam Simko <notifications@github.com> wrote:

> could you also upload the mcor_s2s dataset?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taiyun/corrplot/issues/67#issuecomment-227677305>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATIhPlgcMAbdpxSknA0SH3j9N7Opdx8Vks5qOPKRgaJpZM4I6cSK>
> .
>

RE	S1	S2	S3	S4	S5	S6
T1	0.614511751222766	0.161145023934361	0.006396973317004	0.002300473190896	0.000570649663807	0.003426992337587
T2	2.315462721301360	11.076870332566300	12.733976928402600	18.238031911785500	9.717478585884020	9.176991620524640
T3	0.895224215632694	0.138823836611550	0.079909026601376	0.051272634429616	0.112816797890058	0.126397282635391
T4	0.137541812765603	0.139891774045065	0.127451314694140	0.100402332675211	0.102317340917098	0.126435048504210
T5	0.016656143731560	0.000831279326243	0.026112461979506	0.008045005949484	0.008540385085697	0.007797587886522
T6	0.007134726167765	0.004069607925387	0.039499612539489	0.002613733751500	0.001263923729717	0.003416956047165
T7	0.053419133103823	0.002628560931343	0.050591647803551	0.001067958255233	0.000227169916868	0.003602449968675
T8	0.268371065669020	0.235717578190140	0.153102693587380	0.160562942803836	0.077296033674739	0.120213109851161
T9	0.001106718699550	0.002877166975642	0.019471520369795	0.006289293311256	0.064405696378411	0.101596242070701
T10	0.485636329739813	0.317144019672770	0.384045583490801	0.113306144821885	0.138525769741844	0.190924543674108
T11	1.573381520613380	23.153884344696800	7.928153070929690	3.824748286423720	0.315108743650744	0.725804828315317
T12	2.111907251062230	17.868602216392400	9.280431250155290	7.723522577015850	1.513298496907370	1.695207024873570
T13	0.009111584241773	0.009898509390869	0.006968811492080	0.020913377291175	0.042140064363651	0.020175506543103

**Comment by jinkeanlim** [comment]
lol

The *number.digits = 3* will show the value as 0.999

Could the *number.digits = 2 *will show the value as 0.99 instead 1. Would
it possible to show 0.99 in this case?

**Comment by jinkeanlim** [comment]
lol 

The **_number.digits = 3_** will show the r value as 0.999 in the plot.

Could the **_number.digits = 2_** will show the value as 0.99 instead 1. 

Would it possible in this case?

**Comment by vsimko** [comment]
Mathematically correct is that 0.9991 rounded to 3 digits is 0.999 but the same rounded to 2 digits is 1.0
The question then is, whether we want to render numbers **"rounded"** or **"cropped"** to N decimal places.

**Comment by taiyun** [comment]
rounded

**Comment by jinkeanlim** [comment]
> whether we want to render numbers "rounded" or "cropped" to N decimal places.

@vsimko  this is a nicely put! 

May I suggest both?

**Comment by jinkeanlim** [comment]
@vsimko the s2s dataset

RE | S1 | S2 | S3 | S4 | S5 | S6 
--- | --- | --- | --- | --- | --- | --- 
T1 |0.614511751222766 | 0.161145023934361 | 0.006396973317004 | 0.002300473190896 | 0.000570649663807 | 0.003426992337587 
T2 | 2.315462721301360 | 11.076870332566300 | 12.733976928402600 | 18.238031911785500 | 9.717478585884020 | 9.176991620524640 
T3 | 0.895224215632694 | 0.138823836611550 | 0.079909026601376 | 0.051272634429616 | 0.112816797890058 | 0.126397282635391 
T4 | 0.137541812765603 | 0.139891774045065 | 0.127451314694140 | 0.100402332675211 | 0.102317340917098 | 0.126435048504210 
T5 | 0.016656143731560 | 0.000831279326243 | 0.026112461979506 | 0.008045005949484 | 0.008540385085697 | 0.007797587886522 
T6 | 0.007134726167765 | 0.004069607925387 | 0.039499612539489 | 0.002613733751500 | 0.001263923729717 | 0.003416956047165 
T7 | 0.053419133103823 | 0.002628560931343 | 0.050591647803551 | 0.001067958255233 | 0.000227169916868 | 0.003602449968675 
T8 | 0.268371065669020 | 0.235717578190140 | 0.153102693587380 | 0.160562942803836 | 0.077296033674739 | 0.120213109851161 
T9 | 0.001106718699550 | 0.002877166975642 | 0.019471520369795 | 0.006289293311256 | 0.064405696378411 | 0.101596242070701 
T10 | 0.485636329739813 | 0.317144019672770 | 0.384045583490801 | 0.113306144821885 | 0.138525769741844 | 0.190924543674108 
T11 | 1.573381520613380 | 23.153884344696800 | 7.928153070929690 | 3.824748286423720 | 0.315108743650744 | 0.725804828315317 
T12 | 2.111907251062230 | 17.868602216392400 | 9.280431250155290 | 7.723522577015850 | 1.513298496907370 | 1.695207024873570 
T13 | 0.009111584241773 | 0.009898509390869 | 0.006968811492080 | 0.020913377291175 | 0.042140064363651 | 0.020175506543103

**Comment by taiyun** [comment]
You can format the data before plot it.

**Comment by jinkeanlim** [comment]
I see. Good to know.

**Comment by vsimko** [comment]
Assuming your dataset is stored as a `s2s` matrix and you want to crop the numbers to 2 digits, here is the code that work:
``` r
M <- cor(s2s)
M <- M - sign(M) * (abs(M) %% 0.01)
corrplot(M, method = "circle", type = "upper", order = "original",
         addCoef.col = "white", number.cex = 0.8,
         sig.level = 0.05, insig = "blank", diag = FALSE)
```
![image](https://cloud.githubusercontent.com/assets/7080773/16266365/d419e690-3884-11e6-8d45-0f5ffcb0fdf3.png)

**Comment by jinkeanlim** [comment]
@vsimko thank you!

**Comment by AtomicNess123** [comment]
> ```r
> M <- M - sign(M) * (abs(M) %% 0.01)
> ```

But this wouldn't round it up, would it?

**Comment by HanZhang-psych** [comment]
> Assuming your dataset is stored as a `s2s` matrix and you want to crop the numbers to 2 digits, here is the code that works as you would expect:
> 
> ```r
> M <- cor(s2s)
> M <- M - sign(M) * (abs(M) %% 0.01)
> corrplot(M, method = "circle", type = "upper", order = "original",
>          addCoef.col = "white", number.cex = 0.8,
>          sig.level = 0.05, insig = "blank", diag = FALSE)
> ```
> 
> ![image](https://cloud.githubusercontent.com/assets/7080773/16266365/d419e690-3884-11e6-8d45-0f5ffcb0fdf3.png)

But what if I want to display .40 instead of .4? If the number of rounded digits = 2 it would be consistent if it is .40 instead of .4.
