### ISSUE TITLE
ability to define plot ranges

### ISSUE THREAD

**Issue by udf2457** [taiyun/corrplot#68]
Hi,

Not sure if I've missed this in the documentation, but it would be nice to be able to define plot ranges.

For example, if I'm not interested in extreme correlations +1/-1 and, for the purposes of clarity, I wanted to remove those from the plot and concentrate on, say, the 0.6/-0.6 range there is currently no mechanism in corrplot to do that (as far as I can tell).

**Comment by vsimko** [comment]
I'll try to look into this. You can help me by providing a minimal reproducible example - R code.
In ideal case with a desired output image (could be photoshoped).
