### ISSUE TITLE
How to change plot margins for corrplot.mixed

### ISSUE THREAD

**Issue by tungmilan** [taiyun/corrplot#69]
I couldn't find any option to expand the margins for plot generated by corrplot.mixed. How can I do it? Thanks!

I'm using ver 0.79 2016-08-17 Github (taiyun/corrplot@ab158bb)

![correlation](https://cloud.githubusercontent.com/assets/6590141/17723520/a0e3d89e-63ef-11e6-9f3d-000323af9cb3.png)

**Comment by garyfeng** [comment]
Second that.

**Comment by dAxIOnG8** [comment]
I meet the same problem!

**Comment by taiyun** [comment]
Fixed. Please try again.
