### ISSUE TITLE
Enable to plot a matrix with NA

### ISSUE THREAD

**Issue by 3100** [taiyun/corrplot#7]
Hi, I start using `corrplot` and appreciate for this nice package, but it might be better if `corrplot()` can plot a matrix with NA values.
it throws an error like below:

``` r
> M
     [,1] [,2]
[1,]    1   NA
[2,]   NA    1
> corrplot(M)
Error in if (min(corr) < -1 - .Machine$double.eps^0.75 || max(corr) >  : 
  missing value where TRUE/FALSE needed
```

it may be a simple solution to plot nothing if a cell value is NA.
Thanks in advance.

**Comment by paultanger** [comment]
Any progress on this?

**Comment by fernandojunior** [comment]
+ 1

**Comment by gdkrmr** [comment]
+1 for this

**Comment by kithp** [comment]
It seems this bug hasn't been fixed in the case when is.corr = F.

x = matrix(0, ncol=5, nrow=5)
x[1,1] = NA
corrplot(x)  #this works
corrplot(x, is.corr=F)  #this does not

**Comment by vasselai** [comment]
The bug still persists when one specifies `cl.lim`:

```
x <- matrix(0, ncol=5, nrow=5)
x[1,1] <- NA
corrplot(x)  #this works
corrplot(x, cl.lim=c(0,1))  #this does not
```
