### ISSUE TITLE
NA errors when is.corr = F

### ISSUE THREAD

**Issue by kithp** [taiyun/corrplot#70]
It seems this bug #7 hasn't been fixed in the case when `is.corr = F`.

```r
x <- matrix(0, ncol = 5, nrow = 5)
x[1,1] <- NA
corrplot(x) #this works
corrplot(x, is.corr = F) #this does not
```

**Comment by vsimko** [comment]
I fixed the issue and created a pull request.
Once @taiyun checks that my changes do not break backward compatibility, we can mark this issue as closed.
