### ISSUE TITLE
corrplot.mixed with black color correlation coefficient 

### ISSUE THREAD

**Issue by jcberny** [taiyun/corrplot#76]
Is there any way to have the correlation coefficients colored in black instead in in red and blue in the `corrplot.mixed` plots?

**Comment by vsimko** [comment]
In my development fork, I added two new parameters `lower.col` and `upper.col`.
```r
M <- cor(mtcars)
corrplot.mixed(M, lower.col = "black", number.cex = .6, tl.cex=.8)
```
![image](https://cloud.githubusercontent.com/assets/7080773/22799434/0b29d126-ef06-11e6-97b8-3322e94411ac.png)
