### ISSUE TITLE
error when the matrix(corr) contains NA values.

### ISSUE THREAD

**Issue by mkim0710** [taiyun/corrplot#77]
Hi, I would like to plot some other pairwise statistics (e.g. odds ratio) with `corrplot()` with `is.corr = F` option.

I found out that your codes makes following error when the `matrix(corr)` contains `NA` values.

```
# Error in if (max(corr) * min(corr) < 0) { : 
#   missing value where TRUE/FALSE needed
```
I tried following modification adding `na.rm = T` on your `corrplot()` codes:

    if (!is.corr) {
        if (max(corr, na.rm = T) * min(corr, na.rm = T) < 0) {
            intercept <- 0
            zoom <- 1/max(abs(cl.lim))
        }
        if (min(corr, na.rm = T) >= 0) {
            intercept <- -cl.lim[1]
            zoom <- 1/(diff(cl.lim))
        }
        if (max(corr, na.rm = T) <= 0) {
            intercept <- -cl.lim[2]
            zoom <- 1/(diff(cl.lim))
        }

However, after I modified, I got a new error as follows:
```
# # Error in (n + 1 - n2):(n + 1 - n1) : result would be too long a vector
# # In addition: Warning messages:
# # 1: In min(corr, na.rm = TRUE) :
# #   no non-missing arguments to min; returning Inf
# # 2: In max(corr, na.rm = TRUE) :
# #   no non-missing arguments to max; returning -Inf
# # 3: In max(Pos[, 2]) : no non-missing arguments to max; returning -Inf
# # 4: In min(Pos[, 2]) : no non-missing arguments to min; returning Inf
```

Please let me know your advice.

Thanks.

**Comment by vsimko** [comment]
Hi @mkim0710,
could you provide a sample R-code which demonstrates the problem?
This would simplify debugging.

For example something like this:
```r
library(corrplot)
m <- mtcars
m[1,1] <- NA # adding some NAs
m[3,5] <- NA # adding some NAs
corrplot(cor(m))
```
![image](https://cloud.githubusercontent.com/assets/7080773/22646633/a04aa3de-ec6d-11e6-99c2-84f8ced003da.png)

**Comment by mkim0710** [comment]
Hi vsimko,

Thanks for your reply.

Using mtcars data, I tried as follows:


library(corrplot)
m <- mtcars
m

function.OR = function(v1, v2) {
  tmp.mat = matrix(nrow = 2, ncol = 2)
  tmp.mat[1,1] = length(which(v1 <= mean(v1) & v2 <= mean(v2)))
  tmp.mat[1,2] = length(which(v1 <= mean(v1) & v2 > mean(v2)))
  tmp.mat[2,1] = length(which(v1 > mean(v1) & v2 <= mean(v2)))
  tmp.mat[2,2] = length(which(v1 > mean(v1) & v2 > mean(v2)))
  OR = tmp.mat[1,1] * tmp.mat[2,2] / tmp.mat[1,2] / tmp.mat[2,1]
  OR
}

tmp.mat = matrix(nrow = ncol(m), ncol = ncol(m))
tmp.mat

for (i in 1:nrow(tmp.mat)) {
  for (j in i:nrow(tmp.mat)) {
    tmp = function.OR(m[[i]], m[[j]])
    tmp.mat[i,j] = tmp
    tmp.mat[j,i] = tmp
  }
}

corrplot(tmp.mat, is.corr = F)
# > corrplot(tmp.mat, is.corr = F)
# Error in if (max(corr) * min(corr) < 0) { : 
#   missing value where TRUE/FALSE needed


tmp.mat2 = tmp.mat
tmp.mat2[is.infinite(tmp.mat2)] = NA
corrplot(tmp.mat2, is.corr = F)
> corrplot(tmp.mat2, is.corr = F)
# Error in if (max(corr) * min(corr) < 0) { : 
#   missing value where TRUE/FALSE needed

Thank you very much.

**Comment by vsimko** [comment]
Just to doublecheck.
Do you realize that your matrix `tmp.mat` contains "Inf" instead of "NA" ?

Which version of corrplot are you using ?
```r
# call this to see the version
packageVersion("corrplot")
```

**Comment by mkim0710** [comment]
Hi vsimko,

Thanks for your reply.

Yes, tmp.mat2 is converting Inf into NA.

My package version is as follows:
> packageVersion("corrplot")
[1] ‘0.77’

Thanks.

**Comment by vsimko** [comment]
I'm using version `0.80`, there calling your last command:
```r
corrplot(tmp.mat2, is.corr = F)
```
produces the following plot:
![image](https://cloud.githubusercontent.com/assets/7080773/22650528/e2d342bc-ec7f-11e6-89d1-16e514485793.png)

is it what you would expect ?

**Comment by mkim0710** [comment]
Hi vsimko,

Thanks for your reply.

May I ask how can I install the version 0.80? I installed through install.packages("corrplot").

Thanks.

**Comment by vsimko** [comment]
try this:
```r
install.packages("devtools")
devtools::install_github("taiyun/corrplot", build_vignettes = TRUE)
```

**Comment by mkim0710** [comment]
Hi vsimko,

Thank you so much.

**Comment by vsimko** [comment]
You're welcome.
Don't forget to properly cite `corrplot` in your papers. The R command `citation` show you how to cite it.
```r
library(corrplot)
citation("corrplot")
```
It currently shows something like:
```
To cite corrplot in publications use:

  T. Wei and V. Simko (2016). R package 'corrplot': Visualization of a correlation matrix
  (Version 0.80). Available from https://github.com/taiyun/corrplot

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {R package 'corrplot': Visualization of a correlation matrix},
    author = {Taiyun Wei and Viliam Simko},
    year = {2016},
    note = {(Version 0.80)},
    url = {https://github.com/taiyun/corrplot},
  }

```

**Comment by mkim0710** [comment]
Sure I will not forget to properly cite corrplot package. 

Thanks so much for developing this great package. I really like your design!
