### ISSUE TITLE
Include `cor.mtest` function into base corrplot

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#82]
I saw that the `cor.mtest` function is being used:
- in our vignette
- in @kassambara's blog
- in stackoverflow question http://stackoverflow.com/questions/26574670

Maybe we should include it to corrplot as a function.

**Comment by kassambara** [comment]
Hi,

This would be great.

I think that the corrplot package is a place where we expect to have such functionality even if it's possible to compute the matrix of correlations and p-values using the `Hmisc::rcorr()` function.

One problem with `Hmisc::rcorr()` is that, it doesn't support kendall correlation method.



```r
library(Hmisc)
res <- rcorr(as.matrix(mtcars[, 1:5]), type = "pearson")

res$r # the matrix of correlations
res$P # the matrix p-values
```
