### ISSUE TITLE
List of corrplot disadvantages

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#85]
from: http://cos.name/wp-content/uploads/2009/12/An-Introduction-to-Matrix-Visualization-and-corrplot-Package.pdf

Disadvantages:
- Lack seriation method
- Slow and sucks when handle large matrix

The question is whether the speed is still a problem and what can we do about it.

**Comment by taiyun** [comment]
* corrplot support several matrix reorder methods, and seriation package is suggested to do more.
*The base graphics device is slow.
