### ISSUE TITLE
Axis labels and legend overlap corrplot with type = "upper" and only NAs in external col/rows

### ISSUE THREAD

**Issue by Doi90** [taiyun/corrplot#94]
Hello,

I'm trying to make corrplots of type = "upper" and diag = FALSE, but for datasets where I end up with only NA values in the "external" (first/last) rows/columns of the matrix I run in to an issue where the axis labels and legend overlap to plot. The NA values still get plotted, but rows/columns that had only NA values don't get labelled. You could say the plot "zooms in" on the non-NA data.

Is there a way around this problem? I'm running a model comparison over multiple datasets so I need to keep my corrplots the same dimension with some NA values rather than dropping rows/columns to make the figure play nice.

A reproducible example:
```r
m <- mtcars
m[1,1] <- m[1,11] <- NA # adding some NAs

corrplot(cor(m), type = "upper")   # plot displays correctly becaue there are
                                   # values in [1,1] & [11,11] from the diagonal
```
![working_corrplot](https://cloud.githubusercontent.com/assets/13193240/26388412/6abbb77a-4097-11e7-9e62-79798ea646bc.png)
```r
corrplot(cor(m), type = "upper", diag = FALSE)  # plot displays incorrectly
```
![not_working_plot](https://cloud.githubusercontent.com/assets/13193240/26388414/71d33344-4097-11e7-8a74-40381af0e9c3.png)

**Comment by vsimko** [comment]
fixed in v0.84
```r
m <- mtcars
m[1,1] <- m[1,11] <- NA # adding some NAs
corrplot(cor(m), type = "upper")
```
![image](https://user-images.githubusercontent.com/7080773/29781397-60f4b002-8c19-11e7-9bd5-3c453033f8e5.png)
```r
corrplot(cor(m), type = "upper", diag = FALSE)
```
![image](https://user-images.githubusercontent.com/7080773/29781452-857115ce-8c19-11e7-93e9-b1660d42384b.png)
