### ISSUE TITLE
Label positions incorrectly computed if there are NAs in cells

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#96]
```r
cor(mtcars) -> M
M[1,2:3] <- NA
corrplot(M, diag=FALSE, type="upper")
```
![image](https://user-images.githubusercontent.com/7080773/27145770-2a770182-5137-11e7-8f26-f0ac5bad97d2.png)

**Comment by vsimko** [comment]
I think there is some problem while computing the size of the grid. If there are all NA values in a row or column, then the grid is trimmed and the result is a smaller grid which then overlaps with the labels.
At the moment, I don't know exactly where this is computed.

**Comment by taiyun** [comment]
The size of grid is n by n. You can print  xy-coordinate on the graph to see the details,
``` 
text(1:n, n:1, paste(1:n, n:1, sep='.'))
```

**Comment by vsimko** [comment]
I already fixed this
![image](https://user-images.githubusercontent.com/7080773/29775344-26d5bfba-8c05-11e7-889c-4425acffeb8b.png)

However, now the following code does not render well (due to `na.label = FALSE`):
```r
cor(mtcars) -> M
M[1,2:3] <- NA
corrplot(M, diag=FALSE, type="upper", na.label = FALSE)
```
![image](https://user-images.githubusercontent.com/7080773/29775324-14fd0776-8c05-11e7-9635-2663f8a8099e.png)
