### ISSUE TITLE
Size and of plot and/or square

### ISSUE THREAD

**Issue by pgmikhael** [taiyun/corrplot#97]
Hi! 

I'm plotting a correlation plot with 10 variables using method="number." I'm trying to export the plot with large font sizes (number.cex = 3, tl.cex = 3) for publication purposes, but the squares do not increase in size to accommodate the large font. Is there a way to modify this?

**Comment by vsimko** [comment]
I'm not sure why you need cex=3, but try this:
```r
pdf('my_out.pdf', width = 20, height = 20)
corrplot(cor(mtcars), method = "number", number.cex = 3)
dev.off()
```

**Comment by pgmikhael** [comment]
Hi! 
Thank you for this!

I need the larger fonts because the plot is going to be placed in a figure panel for a science paper, and the text will be too small to read otherwise.

**Comment by vsimko** [comment]
If I were you, I would keep the default value for cex and I would rather experimented with smaller values for `width` and `height` in my example above. Then, I would resize the generated PDF figure as needed inside my LaTeX source using e.g. `\includegraphics[width=0.90\linewidth]{my_out.pdf}`
