### ISSUE TITLE
Chinese display error

### ISSUE THREAD

**Issue by jiangnight** [taiyun/corrplot#98]
![2017-08-09 13 27 02](https://user-images.githubusercontent.com/23185222/29106514-0c3de5d0-7d08-11e7-8822-e470ba256add.png)

Thank you for your contribution,and i meet Chinese display error，how can i solve it

**Comment by taiyun** [comment]
Use showtext package. 
https://cosx.org/2014/01/showtext-interesting-fonts-and-graphs/

**Comment by jiangnight** [comment]
thank you for your help
